### ISSUE TITLE
bug: Disabling dynamic injection causes an error when opening a test file

### ISSUE THREAD

**Issue by ValdezFOmar** [tree-sitter-grammars/tree-sitter-test#2]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-PARSER_NAME

### Describe the bug

After setting `vim.g.tstest_dynamic_injection = false`, an error indicating that a handler for`set-lnaguage-from-grammar!` doesn't exist.

### Traceback

![image](https://github.com/tree-sitter-grammars/tree-sitter-test/assets/80359343/5a455c5b-cedb-4f12-87a2-1496fc18ca78)

### Steps To Reproduce/Bad Parse Tree

1. Install the plugin
2. Set `vim.g.tstest_dynamic_injection = false`
3. Open a `test/corpus/*.txt` file

### Expected Behavior/Parse Tree

There shouldn't be any error and no grammar should be injected in the input region of each test.

It seems that the directive is not registered if `vim.g.tstest_dynamic_injection` is false, which causes the error because one injection query uses it.

https://github.com/tree-sitter-grammars/tree-sitter-test/blob/4a27fc54b88a58ea384ddfcf466d64cfef261ef3/plugin/tstest.lua#L42-L44

**Comment by clason** [comment]
Why are you setting that variable?
