### ISSUE TITLE
bug: cannot parse title with newline

### ISSUE THREAD

**Issue by cathaysia** [tree-sitter-grammars/tree-sitter-test#4]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-test

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.22.5

### Describe the bug

cannot parse:

```
===============
name
with
newlines
===============
a
---
(b)

```

### Steps To Reproduce/Bad Parse Tree

no

### Expected Behavior/Parse Tree

no

**Comment by ObserverOfTime** [comment]
Is this something that tree-sitter currently allows?
