### ISSUE TITLE
bug: cannot parse title with suffix

### ISSUE THREAD

**Issue by cathaysia** [tree-sitter-grammars/tree-sitter-test#5]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-test

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.22.5

### Describe the bug

cannot parse:

```
==================asdf\()[]|{}*+?^$.-
First test
==================asdf\()[]|{}*+?^$.-

=========================
NOT A TEST HEADER
=========================
-------------------------

---asdf\()[]|{}*+?^$.-

(a)

==================asdf\()[]|{}*+?^$.-
Second test
==================asdf\()[]|{}*+?^$.-

=========================
NOT A TEST HEADER
=========================
-------------------------

---asdf\()[]|{}*+?^$.-

(a)

=========================asdf\()[]|{}*+?^$.-
Test name with = symbol
=========================asdf\()[]|{}*+?^$.-

=========================
NOT A TEST HEADER
=========================
-------------------------

---asdf\()[]|{}*+?^$.-

(a)

```

### Steps To Reproduce/Bad Parse Tree

no

### Expected Behavior/Parse Tree

no

**Comment by ObserverOfTime** [comment]
This parser is more restrictive and expects the suffix to be a single repeating character.

**Comment by cathaysia** [comment]
this code is copy from tree-sitter/cli.
should we drop that test?
